alephdata/followthemoney

- followthemoney/schema/Contract.yaml
- followthemoney/schema/ContractAward.yaml
- followthemoney/schema/License.yaml
Rename Concession to License; change to inherit ContractAward and License
from Contract which is changed to extend Asset and Interval.
> Add License

- followthemoney/dedupe/linker.py
- followthemoney/namespace.py
- followthemoney/schema/Document.yaml
- followthemoney/types/entity.py
- followthemoney/util.py
- integrate/followthemoney_integrate/model.py
- tests/dedupe/test_linker.py
- tests/test_namespace.py
- tests/test_proxy.py
- util/followthemoney_util/aggregate.py
Implements #35 but does not make it mandatory
> Namespaces

- followthemoney/export/csv.py
- followthemoney/export/excel.py
- followthemoney/proxy.py
- setup.py
- tests/export/test_csv.py
- tests/export/test_excel.py
- util/followthemoney_util/__init__.py
- util/followthemoney_util/csv.py
- util/followthemoney_util/excel.py
- util/setup.py
> CSV and Excel exporters

- js/src/entity.ts
- js/test/entity.test.ts
Added setCaption function to entity to set the first caption property with the provided value
> Entity Set Caption Function

- followthemoney/schema/Document.yaml
Updated document.yml schema file, with two additional properties (peopleMentioned & companiesMentioned)
> updated document schema

- js/src/schema.ts
- package-lock.json
@pudo I set "label" to be optional, but wasn't quite sure
> Added "directed" and "label" properties to edge ts spec

- followthemoney/schema/Thing.yaml
- followthemoney/types/common.py
- followthemoney/types/country.py
- followthemoney/types/language.py
- followthemoney/types/topic.py
- setup.py
- tests/test_proxy.py
- tests/types/test_topic.py
Refs #163. This is as simple as I could imagine, any concerns?
> Implement topics

- followthemoney/graph.py
Reverts https://github.com/alephdata/followthemoney/commit/7723f2ac7bc9606efa1e0f31a89c6c7cdbdcdf63
refs #181
> Revert "Make property expansion optional when adding a node"

- followthemoney/schema/Payment.yaml
In order to link payment made as per contracts
> Add Contract to Payment

- followthemoney/compare.py
- followthemoney/model.py
- followthemoney/property.py
- followthemoney/proxy.py
- followthemoney/schema.py
- followthemoney/types/common.py
- followthemoney/util.py
Only if you're cool with making ftm python 3.7+ only, but that would fix the circular imports.
> Use __future__, fix tests

- followthemoney/export/misp.py
- setup.py
- tests/export/test_misp.py
> new: MISP exporter

- followthemoney/types/url.py
- tests/types/test_urls.py
As it pops up from time to time (e.g. https://github.com/alephdata/followthemoney/issues/280) i am opening this here for discussion.
I don't know if this is a "bug" or for any other reason an intended feature?
> Don't drop url fragments?

- followthemoney/schema/Mention.yaml
- followthemoney/schema/Thing.yaml
References https://github.com/alephdata/aleph/issues/1267
> Document excerpt-ish.

- followthemoney/types/name.py
- tests/types/test_names.py
Try to select more culturally appropriate names for entities which have multiple names.
> Improve golden record name selection

- followthemoney/types/country.py
- followthemoney/types/name.py
- tests/types/test_names.py
Sie hat uns Alles gegeben.
Sonne und Wind. Und sie geizte nie.
Wo sie war, war das Leben.
Was wir sind, sind wir durch sie.
Sie hat uns niemals verlassen.
Fror auch die Welt, uns war warm.
Uns schützt die Mutter der Massen.
Uns trägt ihr mächtiger Arm.
Die Partei,
Die Partei, die hat immer recht.
Und, Genossen, es bleibe dabei.
Denn wer kämpft
Für das Recht, der hat immer recht
Gegen Lüge und Ausbeuterei.
Wer das Leben beleidigt,
Ist dumm oder schlecht.
Wer die Menschheit verteidigt,
Hat immer recht.
So, aus leninschem Geist,
Wächst von Stalin geschweißt,
Die Partei, die Partei, die Partei!
> Support East Germany

- followthemoney/schema/Address.yaml
- followthemoney/schema/Sanction.yaml
- followthemoney/schema/Security.yaml
A security in the financial sense: some form of debt, equity, derivatives. 
I subjectively don't think this clashes with `Debt` as a link type, but don't quite know how to make the relation more obvious, either.
> Introduce a Security

- contrib/collisions.py
- followthemoney/schema/Call.yaml
- followthemoney/schema/Contract.yaml
- followthemoney/schema/EconomicActivity.yaml
- followthemoney/schema/Identification.yaml
- followthemoney/schema/Interval.yaml
- followthemoney/schema/Mention.yaml
- followthemoney/schema/Page.yaml
- followthemoney/schema/Passport.yaml
- followthemoney/schema/Person.yaml
- followthemoney/schema/TaxRoll.yaml
- followthemoney/schema/UserAccount.yaml
- followthemoney/schema/Vehicle.yaml
> Detect prop definition collisions

- .github/workflows/build.yml
- Makefile
- followthemoney/cli/mapping.py
- followthemoney/helpers.py
- followthemoney/mapping/csv.py
- followthemoney/mapping/entity.py
- followthemoney/mapping/property.py
- followthemoney/mapping/query.py
- followthemoney/model.py
- followthemoney/proxy.py
- followthemoney/schema.py
- followthemoney/types/entity.py
- followthemoney/types/name.py
This should accelerate mapping runs, and also fix a bug in the `map-csv` cli command.
> Mappings tuning

- followthemoney/types/language.py
Support injection of Khmer language files. 
https://github.com/alephdata/aleph/issues/1986
> Add Khmer 'khm' language injestion support

- followthemoney/ontology.py
Remnant from https://github.com/alephdata/followthemoney/commit/e3d957f54d1b1ce1c675b0cc38dd2a4efea0c046
> Fix import error in ontology module

- followthemoney/schema/LegalEntity.yaml
- followthemoney/schema/Thing.yaml
- followthemoney/schema/Vessel.yaml
- tests/test_proxy.py
Fixes #526
I find it sort of difficult to reason about the consequences of this, but it's probably not fatal. For example, it might make the titles of spreadsheet tabs show up in the `name` facet in search :)
> Make Thing.name type name

- followthemoney/offshore.py
This is maybe a bit provocative but could be a fun form of analysis.
> Tag companies as offshores

- followthemoney/helpers.py
- followthemoney/util.py
- tests/test_helpers.py
- tests/test_util.py
> Helper to build person names from parts

- followthemoney/schema/Person.yaml
- followthemoney/types/__init__.py
- followthemoney/types/gender.py
- js/package-lock.json
Fully conscious I'm going to hell for this - it has proven a super helpful feature in training an entity matcher.
> Introduce a prop type for gender

- followthemoney/schema/Similar.yaml
The philosophers have hitherto only interpreted the world in various ways. 
The point, however, is to change it.
> Similar schema for soft entity merges

- followthemoney/helpers.py
- followthemoney/schema/Post.yaml
> Post schema and helper method

- followthemoney/compare.py
- followthemoney/types/name.py
- setup.py
> Remove dependency on fuzzywuzzy

- followthemoney/schema/Identification.yaml
cf. https://github.com/opensanctions/opensanctions/issues/240
> Fix inverse name typo

- followthemoney/proxy.py
This method would be super useful to have in terms of being able to introduce error logging/warnings on invalid properties in nomenklatura. Shouldn't have any negative effects upstream.
> Introduce a cleaning method for sub-classing

- README.md
Just thought I'd add the basic steps I used to get a local setup to develop in.
> Added local dev env steps to the README

- README.md
Fixes #874, based on https://stackoverflow.com/questions/3745135/push-git-commits-tags-simultaneously and on https://stackoverflow.com/questions/1404796/how-can-i-get-the-latest-tag-name-in-current-branch-in-git to get the latest tag.
> Release steps: simultaneously push tags and commits

- .github/workflows/build.yml
> Pin the pypi publish gh action to a release branch

- followthemoney/schema.py
There's only about 200 outcomes of this, and it gets called in a bunch of hot loops.
> Cache schema.is_a calls

- .github/FUNDING.yml
Discovered this option the other day, should probably be on all OCCRP repos.
> Create custom funding link

- followthemoney/schema/Company.yaml
This is a bit of denormalisation, but may make life a lot easier when modelling public companies.
> Add security details to company object

- docs/src/components/common/ReferenceLink.astro
> Fix Python reference URLs

- followthemoney/schema/Person.yaml
- setup.py
* birth country 
* name suffix (e.g. "Jr")
> Two additional props for Person

- followthemoney/schema/Occupancy.yaml
- followthemoney/schema/Position.yaml
> Small fixes for PEP model

- followthemoney/cli/__init__.py
> Disuse pkg_resources, which is deprecated

- followthemoney/schema/Person.yaml
- followthemoney/types/topic.py
- js/src/defaultModel.json
> Persons properties for wanted lists

- followthemoney/schema/Documentation.yml
Follow-up to #1488; seems I missed this one.
> Documentation schema: use array for extends

- followthemoney/proxy.py
- followthemoney/types/checksum.py
- followthemoney/types/common.py
- followthemoney/types/country.py
- followthemoney/types/date.py
- followthemoney/types/gender.py
- followthemoney/types/iban.py
- followthemoney/types/identifier.py
- followthemoney/types/ip.py
- followthemoney/types/language.py
- followthemoney/types/phone.py
- followthemoney/types/string.py
- followthemoney/types/topic.py
- followthemoney/types/url.py
- js/src/type.ts
- tests/test_proxy.py
This doesn't actually do anything (i.e. stop `add`), it just creates some benchmark values.
> Max typed value length metadata
