alephdata/followthemoney

followthemoney/__init__.py
Added environmental variable hook into __init__.py to allow customisation of the FTM repo without directly modifying the source.
Users can define the variable FTM_MODEL_PATH in their `aleph.env` file as their root directory. This directory must have a folder called "schema" inside.
=> Added environmental variable hook for schema customisation 

followthemoney/cli/exports.py, followthemoney/export/csv.py, followthemoney/schema/Debt.yaml
It's **much faster** to import into Neo4J this way.
```
IMPORT DONE in 56s 650ms.
Imported:
1204126 nodes
3100220 relationships
86862272 properties
```
Code of the exporter still might be optimized (multiprocessing, memoizing) but so far it has speed similar to vanilla CSV export
=> Here is my attempt to add export to Neo4J CSVs

followthemoney/proxy.py
It's unpleasant when merge fails like this:
```
followthemoney.exc.InvalidData: No common ancestor: <Schema('RingCompany')> and <Schema('UnknownLink')>
real	193m44.560s
user	140m55.059s
sys	41m27.904s
```
so I've made it fail like this:
```
followthemoney.exc.InvalidData: Cannot merge entities with id 91e4a8d4e517dce82ac58bedcbdec8dcf10f55b1: No common ancestor: <Schema('RingCompany')> and <Schema('UnknownLink')>
real	193m44.560s
user	140m55.059s
sys	41m27.904s
```
=> Making error message on merge more informative

js/src/property.ts, js/test/property.test.ts
Currently there is no way to check if a property has a range before calling the getRange() method, which throws an Invalid Schema error.
=> Added hasRange public variable to property

followthemoney/export/graph.py, followthemoney/export/neo4j.py, followthemoney/types/address.py, followthemoney/types/common.py, followthemoney/types/country.py, followthemoney/types/date.py, followthemoney/types/email.py, followthemoney/types/entity.py, followthemoney/types/iban.py, followthemoney/types/identifier.py, followthemoney/types/json.py, followthemoney/types/language.py, followthemoney/types/mimetype.py, followthemoney/types/name.py, followthemoney/types/phone.py, followthemoney/types/string.py, followthemoney/types/url.py
This PR is an alternative implementation of #101. While reviewing that PR I noticed that it was actually a work-around to the fact that node IDs aren't always properly qualified. So I implemented a method for each data type to make a valid node ID. While at it, I decided to also make a second method that would return a nicely-formatted label for a node. This is cool for countries and similar, where we actually have proper labels as metadata.
I also changed the export form for nodes so that any node (no matter what type) will now have a `caption` field that can easily be used as a UI label.
/cc @dchaplinsky
=> Fix up value nodes in Neo4J export

followthemoney/proxy.py, setup.py, tests/test_proxy.py
VIS captions are based on the first value from the list of values. Without some fixed order, caption will change randomly in the UI.
Alternatively, instead of insertion order, we can maintain an order based on insertion count?
=> Maintain the order of property values

followthemoney/schema/Call.yaml, followthemoney/schema/Message.yaml, followthemoney/schema/UserAccount.yaml
I decided not to add a `Communication` schema because the property names sort of vary among Call, Message and Email. For example, for calls we have `caller` as an `LegalEntity`, for Messages it's `sender`, but for emails `sender` is a string right now. And if we change that we have to reprocess a lot of data which I assume is not ideal? Should we make `Communication` just a symbolic class for now? (without any properties of its own)
refs #161
=> Introduce Calls, Messages and UserAccounts

followthemoney/schema/Message.yaml
We don't include `bodyText` in the entity result as it's excluded from ElasticSearch query result by default https://github.com/alephdata/aleph/blob/82fea8b1eba21462b74bdf4dd9eabe0574b234b9/aleph/index/entities.py#L20
=> Remove bodyText from Message caption and featured properties

followthemoney/schema/RealEstate.yaml, followthemoney/schema/Vehicle.yaml
Fixed the case when a mass of irrelevant titles for RealEstate and Vehicle become names.
=> Overwrite name for RealEstate and Vehicle

followthemoney/model.py
A change had to make to get `followthemoney` to work on Windows when used within the aleph application.
=> Fix for Windows

followthemoney/multi_part_proxy.py, followthemoney/proxy.py, tests/test_multi_part_proxy.py
This creates a new EntityProxy subtype that transparently represents multiple underlying proxies. It works by containing a list of constituent proxies, in addition to a list of proxies that definitely don't belong to it. This will serve as a representation for profiles in aleph.
=> Multi Part Proxy

followthemoney/schema/BankAccount.yaml, followthemoney/schema/CryptoWallet.yaml
This fixes #360 by adding support for blockchain wallets. The best alternative would have been to make a crypto wallet into a `BankAccount`, but they do seem to have separate properties. In particular, the `CryptoWallet` is implemented as based on `Value` and `Thing`, but not `Asset` because `CryptoWallets` are much less formally held through relations of ownership. Instead, a `CryptoWallet` has a `holder` of range `LegalEntity`.
=> Cryptocurrency wallets

followthemoney/helpers.py, tests/test_helpers.py
This helps to pick the most precise date for all the properties of an entity.
e.g. if we have both `2020` and `2020-01-05` as a `birthDate`, keep only the precise date.
=> Dates prefix helper

followthemoney/types/date.py, setup.py, tests/types/test_dates.py
This would adopt the `prefixdate` library, which makes some of the logic of the existing date parsing more explicit. When applied, this should:
a) Speed up date processing, both for format-string based parsing and for normal validation. 
b) Truncate prefixes for minutes and seconds from times when they are `00`. 
c) Fix an apparent issue with time zone conversion in `to_datetime`.
=> Adopt prefixdate library for parsing dates

followthemoney/schema/Sanction.yaml
This is to be able to more explicitly preserve UN security council IDs, and make a distinction between the sanctions programme and consequences that a target is facing.
=> Add a few fields to the sanctions model

followthemoney/schema/Trip.yaml
How does this look? @brrttwrks @pudo @jlstro @Rosencrantz 
Also, what do people think about adding a `parent` property to `Event` and `Trip` so that we can nest events and trips to represent a sequence of events as part of a larger event?
refs #616
=> Draft schema for a Trip to model flights etc

followthemoney/schema/Address.yaml
Based on feedback from @ozhyrenkov here's a change to make an Address a Thing. Note that Address (in its common usage) does not describe the presence of another thing at this address, merely the concept of a place. We may need to sooner or later introduce an Address-to-Thing interval to say: "This company was headquartered at this Address from X to Y"....
=> Make Address a Thing

docs/_templates/model.jinja2
Currently, schemata docs aren’t sorted in any way which makes it harder to quickly look up schemata.
=> Sort schemata documentation alphabetically

followthemoney/types/email.py, tests/types/test_emails.py
This came up in https://github.com/alephdata/ingest-file/issues/253. The `str.encode` function may raise an `UnicodeError` which should be handled. In our case any failure to encode the domain as `idna` means the domain name can't be parsed.
Fixes #870
=> Improve domain related email cleanup error handling

Makefile, README.md
It came up yesterday (https://alephdata.slack.com/archives/C042X0MJF7B/p1667407517705589?thread_ts=1667407106.560519&cid=C042X0MJF7B) that `make build` needs to be run before a release is done. 
I added a commit step for the changed translation (&other) files after we make sure the tests pass.
=> Add missing release step: make build

docs/_templates/model.jinja2, followthemoney/proxy.py, followthemoney/schema.py, followthemoney/schema/Assessment.yaml, followthemoney/schema/Contract.yaml, followthemoney/schema/CourtCase.yaml, followthemoney/schema/CryptoWallet.yaml, followthemoney/schema/Document.yaml, followthemoney/schema/Interval.yaml, followthemoney/schema/LegalEntity.yaml, followthemoney/schema/Person.yaml, followthemoney/schema/Security.yaml, followthemoney/schema/Vehicle.yaml, js/src/defaultModel.json, js/src/entity.ts, js/src/schema.ts, js/test/entity.test.ts, js/test/schema.test.ts, tests/test_model.py, tests/test_proxy.py
This adds basic support for temporal extent metadata (#811) to the Python and TS libraries. It also adds helpers to entity proxies to retrieve the temporal start and end:
```python
company = model.make_entity('Company')
company.add('incorporationDate', '2021-01-01')
company.add('dissolutionDate', '2021-12-31')
company.temporal_start # '2021-01-01'
company.temporal_end # '2021-12-31'
event = model.make_entity('Event')
event.add('date', 2022-01-01')
company.temporal_start # '2021-01-01'
company.temporal_end # None
```
```ts
const company = model.createEntity('Company');
company.setProperty('incorporationDate', '2021-01-01');
company.setProperty('dissolutionDate', '2021-12-31');
company.getTemporalStart(); // '2021-01-01'
company.getTemporalEnd(); // '2021-12-31'
const event = …
```
=> Add temporal coverage metadata

followthemoney/types/common.py, followthemoney/types/date.py, followthemoney/types/entity.py, followthemoney/types/iban.py, followthemoney/types/ip.py, followthemoney/types/mimetype.py, followthemoney/types/number.py, followthemoney/types/phone.py, followthemoney/types/topic.py, followthemoney/types/url.py, js/src/defaultModel.json, js/src/type.ts, js/test/type.test.ts, tests/types/test_common.py
We already include schema descriptions in the JSON model, this improves consistency across types and schemata.
I’ve also converted the property type doc strings from reStructuredText to Markdown. I think the main reason for using reST is the current documentation setup is using Sphinx, but we’re mostly moving away from that and Markdown is a more common format.
=> Add property type descriptions to JSON model

followthemoney/schema/Address.yaml
I remember discussions about ftm/aleph should NOT start to implement geo functionality, and I am :100: on this side.
But still, as the Address entity has lat/lon props, it would be useful for some applications to be able to add osm or google place id (as a result from a geocoding process)
I don't now if type should be an identifier?
=> Schema/Address: Add osm / google places id

followthemoney/schema/Identification.yaml, followthemoney/schema/UserAccount.yaml
1. Renamed `Identification:number` label from `Passport number`  to `Document number`.
2. Added `ipAddress` property to `UserAccount`.
=> Fixed Schema for Identification and UserAccount, as described in #952

followthemoney/schema/EconomicActivity.yaml
`EconomicActivity` inherits the `Interval:description` property (labeled "Description") and also defines its own `goodsDescription` property (also labeled "Description"). This leads to confusion when displaying lists of properties in user interfaces.
We may want to reconsider if a separate `goodsDescription` property is necessary. However, this would be a breaking change, so for now I suggest we update the label to be unique.
=> Fix duplicate property label

followthemoney/types/name.py, tests/types/test_names.py
when the `pick` function for `registry.name` receives only "non-name" values, like "-", "(" (which can happen in dirty real world data), the normalized values list is empty which creates (at least on linux, python 3.11) a segmentation fault:
```python
Python 3.11.2 (main, Feb 12 2023, 00:48:52) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from Levenshtein import setmedian
In [2]: setmedian([])
[1]    307409 segmentation fault  ipython
```
In this fix we would return `None` for this case (as seen for other cases in the same function.)
=> Fix levensthein segmentation fault in invalid name picking

docs/index.rst
Read the Docs doesn't allow setting up a proper redirect for the index page, so we need to create a fake index page with a meta redirect tag.
=> Redirect index page to new documentation site

followthemoney/schema/Contract.yaml
`LegalEntity` and `Security` already define `classification` properties that use the `string` type.
The mismatch in property types has caused issues in Aleph (`string` and `text` properties are mapped to `keyword` and `text` properties in ElasticSearch which behave differently).
Alex and I spent some time today double-checking how changing FtM property types affects Aleph’s ES indexes. We were able to confirm that (as changing field types for existing indexes in ES [is not supported](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings)) this won’t affect existing indexes until they are recreated/rebuilt, but it also doesn’t break anything.
So we should be good to go to merge these changes with regards to Aleph.
=> Change type of `Contract:classification` to `string`

.github/workflows/build.yml
The docker job is currently failing on branches, because we skip the registry auth step but still try to push images.
Not sure what the intent here was: Pushing images only for main/releases or pushing images on every commit? Assuming 1) is the case?
=> Only build/push Docker image on main branch and tagged commits

followthemoney/util.py
Due to an assumption made in #1049 - namely, that calling `cast()` (from the `typing` module) would ensure that the return value of `get_locale()` has the correct type, `Locale` - we were seeing the following error in Aleph:
```
Traceback (most recent call last):
File "/aleph/aleph/tests/test_base_api.py", line 16, in test_metadata
res = self.client.get("/api/2/metadata")
File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1242, in get
return self.open(*args, **kw)
File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 219, in open
response = super().open(
File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1196, in open
response = self.run_wsgi_app(request.environ, buffered=buffered)
File …
```
=> Replace cast() with calling Locale() to ensure obj type

followthemoney/model.py, followthemoney/property.py, followthemoney/schema.py
This makes it much harder to serialise entities using pickle, so it's nice to get rid of it.
=> Remove model attribute from Schema and Property

followthemoney/schema/Vehicle.yaml
Aircraft are sometimes deleted (366 de-registrations from the Malta registry since 2012). Add a field for the de-registration date of a vehicle for when this data point is available.
=> Add de-registration date property for vehicles

contrib/benchmarks/bm_create_proxy_cleaned.py, contrib/benchmarks/run.sh, followthemoney/proxy.py, setup.py, tests/test_proxy.py
=> Maintain insert order of property values

docs/package-lock.json, docs/package.json, docs/src/components/explorer/DeprecatedIndicator.astro, docs/src/components/explorer/SchemaProperties.astro, docs/src/components/explorer/SchemataIndexTable.astro, docs/src/pages/explorer/schemata/[name].astro
This shows small warning indicators in schemata and properties tables (and a popup with an explanation on mouseover), and a warning message below the header on schema pages.
**Schemata table:**
***
**Schema details page:**
***
**Properties table:**
(I marked `Thing:address` as deprecated only for demonstration because we currently do not have any deprecated properties.)
=> Display warnings for deprecated schemata and properties

contrib/check_model.py, followthemoney/schema/Debt.yaml
We capitalize the first character everywhere else… Also adds a simple test case to check that all labels in the default model conform to this.
=> Fix property label capitalization

setup.py
I don't see a reason why we should allow `8.1.6` and not newer version < 9. But perhaps I'm missing something?
=> Loosen up click requirement

followthemoney/schema/Thing.yaml
Weak aliases are things like "noms de guerre" (or, handles, like "pudo"). They are names, just shouldn't be included in default matching configurations.
=> Mark weak aliases as type 'name' (matchable: false)

followthemoney/schema/RealEstate.yaml
RealEstate objects can often have children, such as a building has individual apartments. It often happens that modeling this relationship is important for investigations. This commit and future pull request addess the ability for a RealEstate entity to have a parent so journalists can see subunits of a building, or which apartments/subunits are associated with a single parent unit.
=> add parent entity reference property to RealEstate

docs/package-lock.json, docs/package.json, docs/src/components/common/Cards.astro, docs/src/components/explorer/BooleanCard.astro, docs/src/components/explorer/ExplorerNav.astro, docs/src/components/explorer/SchemaInfo.astro, docs/src/components/explorer/SchemaInheritance.astro, docs/src/components/explorer/SchemaProperties.astro, docs/src/components/explorer/SchemaSemantics.astro, docs/src/components/explorer/SchemataIndexTable.astro, docs/src/components/explorer/TypeInfo.astro, docs/src/components/explorer/TypeValues.astro, docs/src/options.json, docs/src/pages/explorer/schemata/[name].astro, docs/src/pages/explorer/types/[name].astro, followthemoney/types/common.py, js/src/defaultModel.json
This PR contains a few small enhancements to the FtM documentation site and the model explorer in particular:
***
The detail pages now contain a new section below the inheritance section with information about the schema:
***
The same information is also displayed on the index page of the model explorer:
***
Similar to schemata, there’s a new info section for property types, too:
***
When searching for a schema property, after navigating to the search result, the property is now highlighted and the page scrolls to make sure that the property is visible. This is useful especially with schemata that have many properties:
***
And a few more minor changes:
* Fixed the alphabetical sorting of schemata and types in the model explorer sidebar.
* Fixed property type descriptions in the exported …
=> Misc model explorer enhancements

.github/workflows/build.yml, js/src/defaultModel.json
This updates the JSON model file after the 3.5.8 release.
I also added a CI check to make sure that file is up-to-date.
=> Update default model & add a check

docs/src/pages/docs/cli.mdx, docs/src/pages/docs/custom.mdx, docs/src/pages/docs/graphs.mdx, docs/src/pages/docs/mappings.mdx, docs/src/pages/index.mdx
It looks like `docs.alephdata.org` is broken for redirects. Using this as an opportunity to update the links to the new docs location.
=> Update links to Aleph documentation

followthemoney/mapping/entity.py, followthemoney/mapping/property.py, followthemoney/proxy.py, tests/test_proxy.py
This is a follow-up to #1404. This PR only includes the changes that improve logging as I agree that completely disabling value cleaning can be dangerous.
=> Improve logging when skipping values or entities in mappings

.github/workflows/discourse.yml
This is in line with what we do for [Aleph](https://aleph.discourse.group/t/aleph-4-0-1-released/124) and [ingest-file](https://aleph.discourse.group/t/ingest-file-4-0-1-released/125). FYI, I hope it's ok with you, @pudo ? 
P.S: to clarify, this is triggered only when a Github Release is created.
=> Post release announcements to Discourse

js/package.json
In ce9fb7b1438c59badd08bf0493bddafa4aa40d35, `declarationDir` was updated from `./dist/types` to `./dist`. However, `typings` in `package.json` weren't updated.
This PR fixes this issue.
=> fix: path to TypeScript declarations

docs/src/components/explorer/SchemaProperties.astro
I broke the properties listings the model explorer in #1630. The current Astro version renders `data-key={false}` as `data-key="false"` whereas the previous version would simply omit the entire attribute in that case.
=> Fix property tables

followthemoney/types/language.py, java/src/main/resources/defaultModel.json, js/src/defaultModel.json
This adds https://iso639-3.sil.org/code/ben to the list of supported languages.
=> Whitelist Bengali language

.github/workflows/build.yml, .github/workflows/docs.yml, followthemoney/compare.py, followthemoney/types/name.py, pyproject.toml, tests/test_compare.py
This is to prepare for the next `rigour` release, which includes all of fingerprint's name normalization functionality.
=> Remove dependency on `fingerprints`

followthemoney/dataset/dataset.py, followthemoney/dataset/util.py, tests/dataset/test_dataset.py
This ensures dataset names are valid. This means:
- only lowercase ascii characters
- no whitespace
- no other special chars than `_`
- no `_` at the beginning or end
- (see test)
=> feat: ensure valid dataset names
